# Gemini RAG Application Configuration
# For full documentation, see: https://pathway.com/developers/templates/rag-customization

# =============================================================================
# LLM Configuration - Gemini 2.5 Flash via LiteLLM
# =============================================================================
$llm: !pw.xpacks.llm.llms.LiteLLMChat
  model: "gemini/gemini-2.5-flash"
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DefaultCache {}
  temperature: 0
  capacity: 8

# =============================================================================
# Embeddings - Gemini native embedder
# =============================================================================
$embedder: !pw.xpacks.llm.embedders.GeminiEmbedder
  model: "models/text-embedding-004"

# =============================================================================
# Document Parser - Unstructured (simpler, fewer dependencies)
# =============================================================================
$parser: !pw.xpacks.llm.parsers.UnstructuredParser {}

# =============================================================================
# Text Splitter - Token-based chunking
# =============================================================================
$splitter: !pw.xpacks.llm.splitters.TokenCountSplitter
  max_tokens: 400

# =============================================================================
# Data Sources
# =============================================================================
$sources:
  # Google Drive source (uncomment and configure when ready)
  # - !pw.io.gdrive.read
  #   object_id: "YOUR_FOLDER_ID"
  #   service_user_credentials_file: "credentials/gdrive-service-account.json"
  #   with_metadata: true
  #   refresh_interval: 30

  # Local file source (for testing)
  - !pw.io.fs.read
    path: "data"
    format: binary
    with_metadata: true

# =============================================================================
# Vector Index - USearch for similarity search
# =============================================================================
$retriever_factory: !pw.stdlib.indexing.UsearchKnnFactory
  reserved_space: 1000
  embedder: $embedder
  metric: !pw.stdlib.indexing.USearchMetricKind.COS

# =============================================================================
# Document Store - Combines all components
# =============================================================================
$document_store: !pw.xpacks.llm.document_store.DocumentStore
  docs: $sources
  parser: $parser
  splitter: $splitter
  retriever_factory: $retriever_factory

# =============================================================================
# Question Answerer - Basic RAG
# =============================================================================
question_answerer: !pw.xpacks.llm.question_answering.BaseRAGQuestionAnswerer
  llm: $llm
  indexer: $document_store
  search_topk: 6

# =============================================================================
# Server Configuration
# =============================================================================
host: "0.0.0.0"
port: 8000

# =============================================================================
# Cache Configuration
# =============================================================================
with_cache: true
terminate_on_error: false
